/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get public auth configuration
         * @description **Access:** `Public` — No authentication required.
         *
         *     Returns the public configuration a client needs to start the Google sign-in flow (currently the Google OAuth client id). No secrets are exposed.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthConfig"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign in with Google
         * @description **Access:** `Public` — No authentication required.
         *
         *     Exchange a Google ID token for a DIU QuestionBank JWT. Existing email → `200`; new user created → `201`. The response shape is the same in both cases.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["GoogleSignIn"];
                };
            };
            responses: {
                /** @description Authenticated — existing user */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthResponse"];
                    };
                };
                /** @description Authenticated — new user created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthResponse"];
                    };
                };
                /** @description Validation failed or bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Invalid or expired Google ID token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the current user
         * @description **Access:** `User` — Requires a bearer token. Open to any signed-in user (admins included).
         *
         *     Returns the user record for the token on the request.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            user: components["schemas"]["User"];
                        };
                    };
                };
                /** @description Missing or invalid bearer token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Resource not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update your own profile
         * @description **Access:** `User` — Requires a bearer token. Open to any signed-in user (admins included).
         *
         *     Updates editable fields on your own account (`name` and/or `username`). Only the fields you send are changed. Email is immutable (it comes from Google).
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ProfileUpdate"];
                };
            };
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            user: components["schemas"]["User"];
                        };
                    };
                };
                /** @description Validation failed or bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Missing or invalid bearer token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Resource not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Username already taken */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/auth/me/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Upload your profile image
         * @description **Access:** `User` — Requires a bearer token. Open to any signed-in user (admins included).
         *
         *     Uploads a new profile image (or replaces the existing one), stored in R2. Accepts PNG, JPEG, GIF, or WebP, max 5 MB. The previous image, if any, is deleted after the swap. The returned `user.image` is an absolute URL.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": components["schemas"]["ImageUploadForm"];
                };
            };
            responses: {
                /** @description Uploaded */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            user: components["schemas"]["User"];
                        };
                    };
                };
                /** @description Validation failed or bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Missing or invalid bearer token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Resource not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Image exceeds the 5 MB size limit */
                413: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Serve an uploaded file
         * @description **Access:** `Public` — No authentication required.
         *
         *     Streams a stored file (e.g. a profile image) from object storage. Keys come from the `image` field on user objects. Responses are immutable and cacheable.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Object key, e.g. `users/<uuid>.png` (may contain slashes). */
                    key: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The file */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "image/*": string;
                    };
                };
                /** @description Resource not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contributors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List contributors
         * @description **Access:** `Public` — No authentication required.
         *
         *     Users who have at least one submission, most prolific first. Paginated.
         */
        get: {
            parameters: {
                query?: {
                    /** @description 1-based page number. */
                    page?: number;
                    /** @description Items per page (max 100). */
                    perPage?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ContributorList"];
                    };
                };
                /** @description Validation failed or bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contributors/{username}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a contributor by username
         * @description **Access:** `Public` — No authentication required.
         *
         *     A single contributor's public profile and total submission count.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The contributor's username. */
                    username: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Contributor"];
                    };
                };
                /** @description Resource not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/filter-options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get filter options
         * @description **Access:** `Public` — No authentication required.
         *
         *     All departments, courses, semesters, and exam types — the lookup entities a client needs to build the questions filter UI.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FilterOptions"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List questions
         * @description **Access:** `Public` — No authentication required.
         *
         *     Questions with their lookup entities and submission count, newest first. Paginated and filterable by `departmentId`, `courseId`, `semesterId`, and `examTypeId`.
         */
        get: {
            parameters: {
                query?: {
                    /** @description 1-based page number. */
                    page?: number;
                    /** @description Items per page (max 100). */
                    perPage?: number;
                    /** @description Filter by departmentId. */
                    departmentId?: number;
                    /** @description Filter by courseId. */
                    courseId?: number;
                    /** @description Filter by semesterId. */
                    semesterId?: number;
                    /** @description Filter by examTypeId. */
                    examTypeId?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["QuestionList"];
                    };
                };
                /** @description Validation failed or bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/questions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a question by id
         * @description **Access:** `Public` — No authentication required.
         *
         *     A single question with its lookup entities and submission count. The submissions themselves are served by `GET /questions/{id}/submissions`.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Question id. */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["QuestionDetail"];
                    };
                };
                /** @description Resource not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/questions/{id}/submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List a question's submissions
         * @description **Access:** `Public` — No authentication required.
         *
         *     **All** submissions for a question (no pagination — a single question has few). Each submission links to its PDF via `pdfUrl` (served by `GET /files/:key`) and includes the contributor, if any.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Question id. */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["QuestionSubmissions"];
                    };
                };
                /** @description Resource not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        GoogleSignIn: {
            idToken: string;
        };
        AuthConfig: {
            /** @description Google OAuth client id, used to initialize Google Sign-In on the frontend. */
            googleClientId: string;
        };
        ProfileUpdate: {
            name?: string;
            username?: string;
        };
        ImageUploadForm: {
            /**
             * Format: binary
             * @description Image file (PNG, JPEG, GIF, or WebP — max 5 MB).
             */
            image: string;
        };
        User: {
            id: number;
            name: string;
            /** Format: email */
            email: string;
            username: string;
            /** @enum {string} */
            role: "admin" | "user";
            /** @description Absolute URL to the profile image, or null if none is set. */
            image: string | null;
            /** @description Unix epoch seconds (UTC) */
            createdAt: number;
        };
        AuthResponse: {
            /** @description JWT — send as `Authorization: Bearer <token>`. */
            token: string;
            user: {
                id: number;
                name: string;
                /** Format: email */
                email: string;
                username: string;
                /** @enum {string} */
                role: "admin" | "user";
                /** @description Absolute URL to the profile image, or null if none is set. */
                image: string | null;
                /** @description Unix epoch seconds (UTC) */
                createdAt: number;
            };
        };
        ErrorResponse: {
            error: string;
            /** @description Field-level details, present on validation failures. */
            issues?: {
                field: string;
                message: string;
            }[];
        };
        PaginationMeta: {
            page: number;
            perPage: number;
            total: number;
            totalPages: number;
        };
        Department: {
            id: number;
            name: string;
            shortName: string;
        };
        Course: {
            id: number;
            departmentId: number;
            name: string;
        };
        Semester: {
            id: number;
            name: string;
        };
        ExamType: {
            id: number;
            name: string;
        };
        FilterOptions: {
            departments: {
                id: number;
                name: string;
                shortName: string;
            }[];
            courses: {
                id: number;
                departmentId: number;
                name: string;
            }[];
            semesters: {
                id: number;
                name: string;
            }[];
            examTypes: {
                id: number;
                name: string;
            }[];
        };
        Contributor: {
            id: number;
            name: string;
            username: string;
            /** @description Absolute URL to the profile image, or null if none is set. */
            image: string | null;
            submissionCount: number;
            /** @description Unix epoch seconds (UTC) */
            createdAt: number;
        };
        ContributorSummary: {
            id: number;
            name: string;
            username: string;
            image: string | null;
        };
        ContributorList: {
            data: {
                id: number;
                name: string;
                username: string;
                /** @description Absolute URL to the profile image, or null if none is set. */
                image: string | null;
                submissionCount: number;
                /** @description Unix epoch seconds (UTC) */
                createdAt: number;
            }[];
            meta: {
                page: number;
                perPage: number;
                total: number;
                totalPages: number;
            };
        };
        QuestionListItem: {
            id: number;
            /** @description Human-readable label, e.g. "Data Structures (CSE), Summer 26, Quiz". */
            title: string;
            submissionCount: number;
            department: {
                id: number;
                name: string;
                shortName: string;
            };
            course: {
                id: number;
                departmentId: number;
                name: string;
            };
            semester: {
                id: number;
                name: string;
            };
            examType: {
                id: number;
                name: string;
            };
        };
        QuestionList: {
            data: {
                id: number;
                /** @description Human-readable label, e.g. "Data Structures (CSE), Summer 26, Quiz". */
                title: string;
                submissionCount: number;
                department: {
                    id: number;
                    name: string;
                    shortName: string;
                };
                course: {
                    id: number;
                    departmentId: number;
                    name: string;
                };
                semester: {
                    id: number;
                    name: string;
                };
                examType: {
                    id: number;
                    name: string;
                };
            }[];
            meta: {
                page: number;
                perPage: number;
                total: number;
                totalPages: number;
            };
        };
        PublicSubmission: {
            id: number;
            section: string | null;
            batch: string | null;
            /** @description Size of the PDF in bytes. */
            fileSize: number;
            /** @enum {string} */
            watermarkStatus: "awaiting" | "completed" | "failed";
            /** @description Unix epoch seconds (UTC) */
            createdAt: number;
            /** @description Absolute URL to the submission PDF, served by `GET /files/:key`. */
            pdfUrl: string | null;
            contributor: {
                id: number;
                name: string;
                username: string;
                image: string | null;
            } | null;
        };
        QuestionDetail: {
            id: number;
            /** @description Human-readable label, e.g. "Data Structures (CSE), Summer 26, Quiz". */
            title: string;
            submissionCount: number;
            department: {
                id: number;
                name: string;
                shortName: string;
            };
            course: {
                id: number;
                departmentId: number;
                name: string;
            };
            semester: {
                id: number;
                name: string;
            };
            examType: {
                id: number;
                name: string;
            };
        };
        QuestionSubmissions: {
            data: {
                id: number;
                section: string | null;
                batch: string | null;
                /** @description Size of the PDF in bytes. */
                fileSize: number;
                /** @enum {string} */
                watermarkStatus: "awaiting" | "completed" | "failed";
                /** @description Unix epoch seconds (UTC) */
                createdAt: number;
                /** @description Absolute URL to the submission PDF, served by `GET /files/:key`. */
                pdfUrl: string | null;
                contributor: {
                    id: number;
                    name: string;
                    username: string;
                    image: string | null;
                } | null;
            }[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
